### ISSUE TITLE
main.java 올렸습니다

### ISSUE THREAD

**Issue by lsh0704** [11mia/GiveUsManJeom#1]
main.java 올렸습니다.
main에서 메뉴 호출 시, 불러오는 함수명 남겨주면 
추후 반영하겠습니다.

**Comment by KimMinYoung0510** [comment]
미선이가 remote repository 열었으니까 
미선이의 repository에서 같이 작업하는거 아닌가요?
우리 다 콜라보레이터이니까요~ 
콜라보레이터는 다 push권한 있으니까요~

**Comment by KimMinYoung0510** [comment]
아 그리고 우리 메모관리 기능이랑, 계산기 기능, 가계부 기능 있잖아요.
이거 기능 다 하나로 합쳐서 homework.java 파일하나에 다 담을 까요?
아니면, MemoManager.java,  Calculator.java, AccountBook.java 이렇게 나눠서  파일 만들까요?

**Comment by lsh0704** [comment]
git init
git remote add origin https://github.com/11mia/GiveUsManJeom
으로 해서 내 별도의 main branch 만들었는데 혹시 미선이 레포로 안보여??
내 계정으로는 미선이 레포 들어가서 branch를 main으로 바꿔주면 업로드한게 보이거든ㅠㅠ
아직 master branch에는 merge 안한상태야!

**Comment by lsh0704** [comment]
한 파일로 만들면 더 간단하긴 하겠다! 나는 파일하나로 만드는게 더 좋긴 하지 다른 애들 의견은 어때?

**Comment by KimMinYoung0510** [comment]
보니까 미선이의 저장소에서 보면 언니로부터 pull request 왔네요~!
언니가 만든 브랜치 이름이 'main' 이거맞죠?
기다려보세요~

아 언니! 저 이슈 2번 올렸어요 ㅎㅎ 미선이랑 민경이의 댓글을 기다려야겠다ㅎㅎ

**Comment by lsh0704** [comment]
main 맞아! 2번 확인하러 갈게~

**Comment by 11mia** [comment]
넵 파일하나로 만드는게 좋을거 같습니다!언니가 한거 마스터로 머지해주세용!

**Comment by lsh0704** [comment]
마스터로 main.java merge 했습니다

**Comment by 11mia** [comment]
꺄~
