### ISSUE TITLE
혹시 merge할 때 수동으로 merge했나요?

### ISSUE THREAD

**Issue by mindobiee** [11mia/GiveUsManJeom#10]
제목 그대로 수동작업 했는지 궁금합니다!

**Comment by KimMinYoung0510** [comment]
저는 수동으로 '$git merge <branch's name>' 이렇게 해주었어요~

**Comment by mindobiee** [comment]
아하 그러면 cmd 창에서만 작업을 하신건가용??

**Comment by KimMinYoung0510** [comment]
네네~ merge 기능 부분 말씀하시는거죠? 네네 cmd창에서 작업하였습니다~

**Comment by mindobiee** [comment]
넹넹 아하 그렇군요 감사해요~ㅎㅎ
