### ISSUE TITLE
혹시 저를 contributer로 승인시켜주실 수 있나요?

### ISSUE THREAD

**Issue by mindobiee** [11mia/GiveUsManJeom#13]
issue tracker 기능에서 labeling을 통해 5번기능인 notify issues to project members를 할 수가 없어요~
그리고 merge를 하고 pull request를 하니까 또 다시 merge되어서 이상한 모양으로 나와서
pull request를 거치지 않고 바로 pull을 하면 번거로움을 덜 할 거 같습니다!

**Comment by 11mia** [comment]
ㅎㅎㅎㅎ콜라보레이터등록은 이미 저~번주에 완료했고 그때 메일에 요청간걸 수락하면 된다능...

**Comment by 11mia** [comment]
ㅎㅎㅎㅎ콜라보레이터등록은 이미 저~번주에 완료했고 그때 메일에 요청간걸 수락하면 된다능...

**Comment by mindobiee** [comment]
아하 ㅋㅋㅋ그렇군용 알겠습니다아~!!
