### ISSUE TITLE
To.mindobiee

### ISSUE THREAD

**Issue by 11mia** [11mia/GiveUsManJeom#16]
1. MainProgram,accountbook 클래스가 지금 둘다 public상태임. 분명 컴파일에러가 뜰텐데 돌려봤는지가 의문. 복붙이 의심됨

2. 가계부기능은 MainProgram내의 메인에서 호출해서 사용하도록 수정할것
3. 가계부기능에서 사용되는 모든 메소드들은 accountbook클래스 안으로 넣어서 사용할것
4.delete에서 Y외의 입력시엔 y나 잘못된 입력인경우에도 기능이 종료되는것으로 보임 YyNn외의 입력시엔 다시 입력받도록 처리하고 y입력시에도 삭제되도록 수정할것
5.item에서 파라미터가 없는 디폴트 생성자 지울것
6. delete에서 항목번호 123외의 숫자입력시 다시입력받도록 처리할것
7. update,delete시에 목록이 비어있거나 목록범위 외의 숫자입력시 처리하기

**Comment by 11mia** [comment]
총 7가지 수정바람

**Comment by mindobiee** [comment]
item에서 디폴트 생성자 지우면 안돌아가던데??
나머지 1,2 번은 수정해서 일단은 돌아가도록 했고, 나머지는 차근차근 수정할게요~

**Comment by lsh0704** [comment]
메인에서 돌려야해요 생성자로 돌리면 안돌아갑니다!

**Comment by mindobiee** [comment]
디폴트 생성자가 필요하지는 않지만 만약에 다른 파라미터가 있는 생성자를 만들게 되면 디폴트가 존재해야 하더라고요
