### ISSUE TITLE
-현 진행상황-

### ISSUE THREAD

**Issue by lsh0704** [11mia/GiveUsManJeom#18]
총 18번의 commits
6개의 issue 진행 중 / 10개가 closed

현재 캡쳐 및 설명 제출 - 강미선
토요일(2일)까지는 레포트를 정리하여 늦어도 일요일(3일) 스노보드에 제출 예정입니다.
<b>## 2일</b>까지 자료 보내주세요.

우선 간단한 code refactoring을 했습니다.

1. 특정 코드들은 들여쓰기가 전혀 안되어 있어 가독성이 떨어지기 때문에 이를 수정하였습니다.
2. // TODO Auto-generated constructor stub 클래스 생성시 초기 문장도 그대로 있어서 삭제했습니다.

코드 merge 시 최소한의 코드 정리 부탁드립니다.

3. 
`System.out.println("  번호    구입날짜      상품명      상품가격   ");`
`System.out.println(" ["+num+"] " + v.get(num).getday()+"  "+v.get(num).getname()+"   
"+v.get(num).getprice());`

이부분이 출력화면에 사용자가 입력한 값에 따라 일정하지 않은 모양으로 출력됩니다.
\t 등을 이용해서 수정부탁드립니다.

![default](https://user-images.githubusercontent.com/31886882/33424861-6d7c9d18-d600-11e7-9bbf-3961506950aa.JPG)

+
메뉴 기능들 위치가 섞여 있어서 기능 순서대로 코드를 정리해볼까 합니다.
메모 - 계산 - 가계부 - 메인 순으로 정리 어떨까요?

**Comment by KimMinYoung0510** [comment]
네 '메모-계산기-가계부-메인'순으로 정리하는거 좋습니다!
저도 제 담당 부분 (메모관리기능) 수정 작업을
좀 하면서 코드를 좀 더 깔끔하게 다듬을 계획입니다.
모두 화이팅합시다:)
캡쳐 및 설명 얼른 보낼게요 !ㅎㅎ

**Comment by mindobiee** [comment]
넵! 재커밋하여 정리했다고 생각했는데 안됐나보네요~ 다음부터 주의하겠습니다.
3번에 제시해주신 출력화면 일정한 모양이 되도록 수정하겠습니다.
코드 정리 부분은 혹시 메인을 제일 앞에다가 두는 건 어떨까요?

**Comment by 11mia** [comment]
넵 계산기 위치 수정할게요!
캡쳐 및 설명 제출 - 강미선 요부분은 냈다는 의미죠...?(놀람)

**Comment by lsh0704** [comment]
그럼 기능하고 메인은 분리해서 코드 리팩토링 하는거네용!
넹 제출했다는 의미입니다!  '현재 캡쳐 및 설명 제출 - 강미선' 으로 수정했습니다

**Comment by lsh0704** [comment]
위 제출기한에서 요일을 잘못 적어서 정정합니다.
!!!!!!!!2일 토요일!!!!!!!!까지 보내주시면 됩니닷

**Comment by KimMinYoung0510** [comment]
네 알겠습니다!!
