### ISSUE TITLE
#2자바 파일 관하여

### ISSUE THREAD

**Issue by KimMinYoung0510** [11mia/GiveUsManJeom#2]
여러분~
소희언니가 
'MainProgram.java'파일 올리고 pull request 보냈네요.

근데 아까 이슈1번에 저가 댓글을 달긴 했지만 
여기다가 다시 올리려구요.

메모관리기능, 계산기기능, 가계부 기능을 다 저 MainProgram.java파일 하나에 담을까요?
아니면 MemoManager.java, Calculator.java, AccountBook.java 파일에 각각
기능을 담을까요?

참고로 소희언니는 저 기능들을 하나의 파일(MainProgram.java)에 다 담으면 편할 것 같다고 했어요.
물론 저도 그렇구요!

여러분의 의견을 댓글로 달아주세요~!

**Comment by 11mia** [comment]
파일하나에 다 담는거에 한표!

**Comment by lsh0704** [comment]
파일 하나에 다 담으면 모두가 편해요~

**Comment by 11mia** [comment]
그럼 파일하나에 다 담는거로!
