### ISSUE TITLE
수정 결과 알립니다

### ISSUE THREAD

**Issue by lsh0704** [11mia/GiveUsManJeom#22]
### 각 기능 클래스마다 주석 달았습니다. ex) // 메모 관리 메뉴, // 메모 생성

기능 전부 확인 결과 정상 작동합니닷
디자인만 수정하면 될 것 같습니다~
1. 이전 이슈에 적은 가계부 출력 시 정렬 부분만 수정하시면 됩니당!
2. 
![1](https://user-images.githubusercontent.com/31886882/33438326-d3f6f1b0-d62d-11e7-89e8-d79e00602931.JPG)

계산기 메뉴 호출 시 
==<계산기 메뉴>==

============

부분만 추가해주시면 될 것 같습니다~

모두 수고하셨습니다 :)

+

**Comment by lsh0704** [comment]
+ 추가 : 무얼 캡쳐할지 모르면 갠톡주세요!

**Comment by mindobiee** [comment]
네~ 수고 많으셨습니다^^

**Comment by 11mia** [comment]
수정했습니당!ㅎㅎ

**Comment by lsh0704** [comment]
넵!!
