### ISSUE TITLE
가계부 기능 기능 수정해주세요!

### ISSUE THREAD

**Issue by 11mia** [11mia/GiveUsManJeom#23]
![image](https://user-images.githubusercontent.com/20166683/33442144-c0ceb096-d637-11e7-8a72-c32f1fa18660.png)
구매내역 삭제에서 NnYy일땐 잘 먹히는데 그 외의 입력시에 다시 입력하라는 출력만 뜨고 기능이 종료가 되어버리는거 수정해주세요!다시 입력하라는 출력뜨고 NnYy입력받을때까지 다시 입력받아서 처리하도록 수정바랍니다~ 이거 말고는 잘 돌아가는듯 합니다.
![image](https://user-images.githubusercontent.com/20166683/33442657-073d57d4-d639-11e7-929d-4570b3d51db5.png)
그리고 리스트에서 번호 구입날짜 상품명 상품가격 출력하는 부분에서 구입날짜뒤에 탭 한번만 더 하는게 보기 좋을 거 같습니다!

**Comment by 11mia** [comment]
아 구입내역의 정보를 입력하세요. 하고 구입날짜 입력받는것도 줄바꿈해서 하면 깔끔할거같네요

**Comment by lsh0704** [comment]
앗 제가 test할때 YNyn 경우 외의 입력은 전혀 생각못했네요 ㅠㅠ

**Comment by mindobiee** [comment]
네 수정할게요~
지금 공백 수정중입니다.

**Comment by KimMinYoung0510** [comment]
아아 그리구 그! 가계부 품목 번호 카운트 할 때 0부터말고, 1부터 카운트 해주시면 감사하겠습니다~

**Comment by mindobiee** [comment]
네 수정할게욥~
가계부 수정할 사항이 많은데 지금 한 번에 작업하기에는 시간이 좀 걸릴 거 같아요~
참고해주세용!
