### ISSUE TITLE
메모관리 기능 수정 부탁할게요!

### ISSUE THREAD

**Issue by mindobiee** [11mia/GiveUsManJeom#25]
처음 <메모관리 메뉴>에서 1-4번 숫자가 아니라 다른 걸 받으면
수정하라고는 나오는데 숫자입력이 안되고 바로 다시 메뉴를 보여주고 있습니다
이것 수정해주세요~
<img width="154" alt="default" src="https://user-images.githubusercontent.com/33727516/33483015-09b64808-d6df-11e7-9d41-0369fce1a0af.PNG">

**Comment by 11mia** [comment]
이건 버그가 아니죠...다시입력하라그러고 메뉴 재출력후 다시 입력을 받는거니까 정상인거죠. 이게 버그면 mindobiee님도 이부분 수정해야할텐데..?

**Comment by KimMinYoung0510** [comment]
![default](https://user-images.githubusercontent.com/33872171/33483966-ac8896f4-d6e3-11e7-86ab-c9b654d893bc.PNG)
민경아 나 숫자 입력 제대로 되는데??
 뭘 고치라는거야??
너랑 나랑 똑같은데?
댓글 달아줘

**Comment by KimMinYoung0510** [comment]
위의 사진은 너가 구현한 가계부!!참고해~

**Comment by mindobiee** [comment]
아하 그러네!! 헙 내가 착각햇다!!
