### ISSUE TITLE
3가지 수정 사항 수정했습니다.

### ISSUE THREAD

**Issue by mindobiee** [11mia/GiveUsManJeom#26]
기능을 수정하고, 이후에 리팩토링 할 예정입니다^^

**Comment by mindobiee** [comment]
앗 그리고 공백처리는 't'을 이용하는데도 계속 문제가 있더라구요..
그래서 일단은 아래처럼 보이도록 수정했습니다.
<img width="222" alt="default" src="https://user-images.githubusercontent.com/33727516/33484194-90f49144-d6e4-11e7-888c-6bdd02b521a7.PNG">

**Comment by lsh0704** [comment]
commit 하기 전에 담당 클래스의 모든 기능을 test 해주시기 바랍니다.
삭제부분이 에러나네요. 자바는 boolean type을 이용해야 합니다.
<img width="557" alt="default" src="https://user-images.githubusercontent.com/31886882/33487329-2c72d940-d6f0-11e7-8d01-116e54584f40.PNG">

**Comment by mindobiee** [comment]
앗 그렇네요..;; 알겠습니닷
