### ISSUE TITLE
master branch에 자바파일명에 관해서

### ISSUE THREAD

**Issue by 11mia** [11mia/GiveUsManJeom#3]
일단 처음에 올려둔 homework.java를 지우고 소희언니가 만든 MainProgram.java만 남겨서MainProgram.java에 쭉 이어서 작업하는게 낫겠죠...?

**Comment by KimMinYoung0510** [comment]
네네~ 그럽시다~

**Comment by lsh0704** [comment]
헉 내가 merge할때 사라져서 잘못한줄알았네 네네 좋아요 근데 이전 README.md는 남겨도 좋았을거같아요~

**Comment by 11mia** [comment]
넵!!ㅎㅎ
