### ISSUE TITLE
이클립스 이용해서 파일 수정할때!

### ISSUE THREAD

**Issue by 11mia** [11mia/GiveUsManJeom#4]
file-import-Git-project from Git이용해서 하면 깃이랑 바로 연동돼서 편합니다아!여기에서 브랜치들 왔다갔다 하면서 파일 수정가능해요!
![image](https://user-images.githubusercontent.com/20166683/33376709-1d3a34c2-d552-11e7-9fa0-d91ef289bb7c.png)
git repository탭에서 브랜치 옮기면 됩니당

**Comment by KimMinYoung0510** [comment]
오 정말 유용한 정보군요!
미선이 고마워요~!

**Comment by lsh0704** [comment]
고맙습니다 (*´ڡ`●)

**Comment by mindobiee** [comment]
오 이클립스에 이런 기능이 있었네요~
고마워요 :-)
