### ISSUE TITLE
지금까지 진행상황 정리

### ISSUE THREAD

**Issue by 11mia** [11mia/GiveUsManJeom#6]
- 메모관리, 계산기, 메인 체크해서 master에 머지해서 푸쉬했습니다:)

**Comment by lsh0704** [comment]
확인했습니다!

**Comment by KimMinYoung0510** [comment]
네네 저도확인했습니다~

**Comment by KimMinYoung0510** [comment]
아아! 그리고 이 버전의 'MainProgram.java'파일에 작성된
'import test222.calculator;'
이 부분 삭제하였습니다:)

**Comment by 11mia** [comment]
감사합니당:)
