### ISSUE TITLE
git 사용+이슈 트래커 사용 캡쳐본

### ISSUE THREAD

**Issue by lsh0704** [11mia/GiveUsManJeom#8]
저한테 캡쳐본 보내주실 때 개인 카톡으로 보내거나
이 곳에 branch 따서 올리면 제가 캡쳐본들 clone하고 branch 삭제하겠습니다 :)

+ 캡쳐마다 세부설명은 ____.txt 파일로 첨부하거나 word 파일로 받겠습니다

**Comment by 11mia** [comment]
엇 언니 이번 과제는 각자 제출아닌가용...?

**Comment by lsh0704** [comment]
앗 민영이랑 대화할때는 내가 합쳐서 내는줄 알았는데..? 내일 교수님한테 여쭤볼게용!

**Comment by 11mia** [comment]
넵!!

**Comment by KimMinYoung0510** [comment]
그래요 교수님께 여쭤봅시다 ㅎㅎ

**Comment by mindobiee** [comment]
네!! 아마도 합쳐서 내는 걸거에요!

**Comment by lsh0704** [comment]
>> 교수님께 여쭤봤는데 파일 하나로 내는거네요! 각자 카톡으로 캡쳐본 설명 보내주세요!! (캡쳐 설명 워드 파일하나로 합쳐서 보내는 것도 가능)

**Comment by 11mia** [comment]
보냈습니다!
